### ISSUE TITLE
[consolidation] MT-173 and MT-18: links

### ISSUE THREAD

**Issue by helenvholmes** [NYPL/nypl-design-system#96] opened 2020-02-26 20:19 UTC
### Components in question:
[MT-173: Text Link](http://themetronome.co/components/mt-173-text-link/?fresh=true)
[MT-18: Text Link w Icon](http://themetronome.co/components/mt-18-text-link-w-icon/?fresh=true)

### Description of issue:
1. I believe these should be atoms, not molecules. Fundamentally `a` tags are the smallest possible unit.
2. These two might potentially be the same component, with adding an icon, and choosing which side it appears on, being flags that the component can be passed instead of having multiple components. Requires a larger discussion with team.

**Comment by hokei** [comment] 2020-05-15 14:44
Closed as dupe of https://github.com/NYPL/nypl-design-system/issues/122

**Closed as completed** 2020-05-18 17:45 UTC
