### ISSUE TITLE
Regression Testing

### ISSUE THREAD

**Issue by hokei** [NYPL/nypl-design-system#345] opened 2020-08-19 18:23 UTC
### Component in question:
- All

### Description of issue:
- Holder for eventual regression testing work.  
- Goal:  Have an automated way to be alerted when regressions happen
- This may contain:  Automated testing in multiple browsers
- snapshot testing

**Comment by helenvholmes** [comment] 2020-09-03 15:48
@hokei, this sounds like a project, not a bug, exactly. Can we close this out until the project is on the roadmap?

**Comment by helenvholmes** [comment] 2020-10-28 14:23
Closing this out as it's an entire project that needs to be prioritized on our [roadmap](https://app.smartsheet.com/sheets/9hC7JwMfgWFV9vfx7hJm5mF8gvJ3phq9JjPHCGg1?view=gantt).

**Closed as completed by helenvholmes** 2020-10-28 14:23 UTC
