### ISSUE TITLE
Update hex colors for styles/research-library

### ISSUE THREAD

**Issue by kat-lac** [NYPL/nypl-design-system#505] opened 2021-01-22 18:26 UTC
### Description of issue:
Update hex colors for following research libraries (styles/research-library): 

- SASB: Dark Red: **760000** (it is currently C60917)

- LPA: Dark Green: **005d53** (it is currently 008375)

- Schomburg: Dark Brown: **a03e31** (it is currently C54B38)

### Component in question (if applicable):
- styles/research-library/lpa
- styles/research-library/schomburg
- styles/research-library/schwarzman

### Figma Link (if applicable):
- [Figma] https://www.figma.com/file/qShodlfNCJHb8n03IFyApM/Main?node-id=15454%3A47007

**Comment by helenvholmes** [comment] 2021-01-27 16:58
Duplicate of [UX-233](https://jira.nypl.org/browse/UX-233)

**Closed as completed by helenvholmes** 2021-01-27 16:58 UTC
